Use wglGetProcAddress on windows to get opengl symbols
jrmuizel/gecko-cinnabar pull request #26
Opened 2016-10-27 22:13 UTC by changm

2016-10-28 15:37 UTC, kvark requested changes

2016-10-28 15:37 UTC, kvark commented on gfx/webrender/src/bindings.rs
> +                // Try opengl32.dll first
Why aren't we prioritizing `wglGetProcAddress` over the direct symbol lookup via `opengl32.dll`?

2016-10-28 15:37 UTC, kvark commented on widget/nsBaseWidget.cpp
> +bool nsBaseWidget::CreateWebrenderLayerManager()
Should be `CreateWebRenderLayerManager` for consistency

2016-10-28 15:37 UTC, kvark commented on widget/nsBaseWidget.cpp
> +  mRootLayerTreeId.value(), apzc);
wrong indentation?

2016-10-28 15:37 UTC, kvark commented on widget/windows/nsWindow.cpp
> +  if (CreateWebrenderLayerManager()) {
So we are creating WRLM every time we call `nsWindow::GetLayerManager()`? Sounds fishy

2016-10-28 15:37 UTC, kvark commented on gfx/gl/GLContextProviderWGL.cpp
> +} /* namespace mozilla */
missing new line

2016-10-28 16:34 UTC, changm commented on gfx/webrender/src/bindings.rs
> +                // Try opengl32.dll first
Because this is the order Gecko is doing in. wglGetProcAddress should also only be used for gl extension functions according to the docs - https://msdn.microsoft.com/en-us/library/windows/desktop/dd374386(v=vs.85).aspx. Gecko only uses it if it detects some extensions (which I think WebRender just assumes these extensions exist) If it's the wrong order, I can switch it but I'm not sure it is. Someone with more opengl expertise can chime in here.

2016-10-28 16:37 UTC, changm commented on widget/nsBaseWidget.cpp
> +  mRootLayerTreeId.value(), apzc);
The rest of the file is 2 spaces.

2016-10-28 16:37 UTC, changm commented on widget/nsBaseWidget.cpp
> +bool nsBaseWidget::CreateWebrenderLayerManager()
Fixed.

2016-10-28 16:38 UTC, changm commented on widget/windows/nsWindow.cpp
> +  if (CreateWebrenderLayerManager()) {
Good catch, thanks!

2016-10-28 17:02 UTC, kvark approved these changes

2016-10-31 20:26 UTC, jrmuizel commented
I merged this manually

2016-10-31 20:26 UTC, closed without merging